### ISSUE TITLE
Cursivas

### ISSUE THREAD

**Issue by Ivanabete** [pdepviernestm/2023-bienvenida-matuaponte#3]
No me gusta que todo esté en cursivas. Considero que las cursivas son para otros usos, como aclaraciones por ejemplo.

**Comment by matuaponte** [comment]
A mi me gustan como quedan por ello las utilizo, considero que los títulos si quedan bien sin cursiva pero el desarrollo lo considero estético y de contraste con cursiva.

**Comment by Ivanabete** [comment]
Me parece bien.
Entonces, considero como que el issue ya está solucionado.
